server:
  port: 18002

eureka:
  instance:
    hostname: discovery.microsrv.docker.pkrss.com
  client: # Not a client, don't register with yourself
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery.microsrv.docker.pkrss.com:${server.port}/eureka/
      # defaultZone: http://user:password@discovery.microsrv.docker.pkrss.com:${server.port}/eureka/

# spring.cloud.config.discovery.enabled: true