

spring:
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 18002
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: discovery.microsrv.docker.pkrss.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery.microsrv.docker.pkrss.com:18002/eureka/

---

spring:
  profiles:
    active: default

---

#
#---
#
#spring:
#  profiles: development
#server:
#  port: 8761
#endpoints:
#  restart:
#    enabled: true
#  shutdown:
#    enabled: true
#  health:
#    sensitive: false
#eureka:
#  instance:
#    hostname: discovery
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/
