server:
  port: 19002

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://pkrss-microsrv-discovery:18002/eureka/
  instance:
    preferIpAddress: true

security:
  basic:
    enabled: false
        
# feign.httpclient.enabled: true

ribbon:
  eureka: 
    enabled: true