server:
  port: 18001

management:
  context-path: /admin
  
eureka:
  instance:
    hostname: pkrss-microsrv-config
    leaseRenewalIntervalInSeconds: 10
    statusPageUrlPath: /admin/info
    healthCheckUrlPath: /admin/health
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://pkrss-microsrv-discovery:18002/eureka/

spring:
  profiles:
    active: native