server:
  port: 19001

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery.microsrv.docker.pkrss.com:18002/eureka/
  instance:
    preferIpAddress: true

security:
  basic:
    enabled: false
        
# feign.httpclient.enabled: true

ribbon:
  eureka: 
    enabled: true