server:
  port: 18004

sidecar:
  port: 18003
  hostname: consul.microsrv.docker.pkrss.com
  health-uri: http://consul.microsrv.docker.pkrss.com:18003/health.json

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
#    hostname: gateway.microsrv.docker.pkrss.com
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://discovery.microsrv.docker.pkrss.com:18002/eureka/

ribbon:
  eureka:
    enabled: true

zuul:
#  prefix: /api
  ignoredServices: '*'
  routes:
    a:
      path: /a/**
      serviceId: pkrss-microsrv-a
      strip-prefix: false
    b:
      path: /b/**
      serviceId: pkrss-microsrv-b
      strip-prefix: false

# hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000